### ISSUE TITLE
点击下载设置闪退

### ISSUE THREAD

**Issue by lixiangwuxian** [EdrowsLuo/BeatmapService#3]
已经给了应用所有权限，在设置内点击“下载设置”即闪退

**Comment by lixiangwuxian** [comment]
一些其他的信息：下载目录均存在，可以确定不是由目录不存在引发的问题。
我并且发现可以通过修改/data/data软件目录下软件的xml配置文件以手动修改下载目录。

**Comment by Exsper** [comment]
colorOS 7.1 Android 10
已给存储权限，可以正常下载，点下载设置闪退
因为也遇到过其他app读路径出错，估计可能是安卓版本兼容问题

**Comment by Exsper** [comment]
新版本问题已解决，谢谢
